version: '3'

services:

  taxi-service-app:
    image: packtpub-spring-boot-2/spring-boot-2-taxi-service:${APP_IMAGE_VERSION}
    build:
      context: .
      dockerfile: ./spring-boot-2-taxi-service/src/main/resources/docker/Dockerfile
      args:
        JAR_FILE: ./spring-boot-2-taxi-service/target/spring-boot-2-taxi-service-${APP_BUILD_VERSION}.jar

    networks:

      - backend

    depends_on:

      - db



  taxi-booking-service-app:
    image: packtpub-spring-boot-2/spring-boot-2-taxi-book-service:${APP_IMAGE_VERSION}
    build:
      context: .
      dockerfile: ./spring-boot-2-taxi-book-service/src/main/resources/docker/Dockerfile
      args:
        JAR_FILE: ./spring-boot-2-taxi-book-service/target/spring-boot-2-taxi-book-service-${APP_BUILD_VERSION}.jar

    networks:

      - backend

    depends_on:

      - db



  db:

    hostname: redis

    image: "redis:alpine"

    ports:

      - "6379:6379"

    networks:

      - backend



  nginx-lb:

    container_name: nginx-lb

    image: nginx:1.13

    restart: always

    ports:

      - 80:80

      - 443:443

    volumes:

      - ./nginx/conf.d:/etc/nginx/conf.d

    networks:

      - backend

    depends_on:

      - taxi-service-app

      - taxi-booking-service-app





networks:

  backend:

    driver: bridge